config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs do
    get :deleted_index, on: :collection
    member do
      get 'content'
      get 'content_edit'
      put :new_network
      patch :new_network
      put :new_interview
      patch :new_interview
    end
  end
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  post '/', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/network.rb
class Network
  include Mongoid::Document
  include Mongoid::Timestamps

  field :date, type: DateTime
  field :done, type: Mongoid::Boolean
  field :plans, type: Mongoid::Boolean

  has_many :contacts
  has_many :notes
  embedded_in :job
end

app/views/networks/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this network from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.fields_for :networks do |n| %>
      <%= n.label :date %><br>
      <%= n.date_field :date %><br>
  </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/networks/_networks.html.erb
<% @networks.each do |n| %>
  Networking:<%= n.date %><br>
<% end %>
  <%= link_to "Discuss with another person", new_network_job_path(@job), method: :put %>