config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs do
    get :deleted_index, on: :collection
    member do
      get 'content'
      get 'content_edit'
      put :new_network
      patch :new_network
      put :new_interview
      patch :new_interview
    end
  end
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  post '/', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/job.rb
class Job
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Timestamps
  field :title, type: String
  field :url, type: String
  field :company_name, type: String
  field :due_date, type: DateTime
  field :type, type: String

  embeds_many :interviews
  embeds_many :networks
  embeds_one :research
  embeds_one :resume
  embeds_one :job_application

  has_many :contacts, as: :contactable
  belongs_to :user
  accepts_nested_attributes_for :research, :networks, :resume, :job_application, :interviews
  after_create :initialize_job

  def initialize_job
    self.research = self.create_research
    self.job_application = self.create_job_application
    self.resume = self.create_resume
    self.networks.create
    self.interviews.create
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :check_authorization
  before_action :set_job, except: [:index, :new, :create, :deleted_index]

  def index
    @jobs = Job.where(user: current_user)
  end

  def show

  end

  def new
    @job = Job.new(user: current_user)
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def update
    if @job.update(job_params)
      #FIXME update success should render step
      render 'jobs/content_view', notice: 'Job was successfully updated.', locals: {step: params[:step]}
    else
      render :edit
    end
  end

  def destroy
    #TODO notice should not report destroyed if archived
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  def content
    render 'jobs/content_view', locals: {step: params[:step]}
  end

  def content_edit
    render 'jobs/content_edit', locals: {step: params[:step]}
  end


  def content
    render 'jobs/content_view', locals: {step: params[:step]}
  end

  def content_edit
    render 'jobs/content_edit', locals: {step: params[:step]}
  end

  def new_network
    @job.networks.create
    redirect_to @job
  end

  def new_interview
    @job.interviews.create
    render 'jobs/content_edit', locals: {step: params['interview']}
  end

  def deleted_index
    #TODO clicking on job list items crashes app
    @jobs = Job.deleted.where(user: current_user).to_a
    render "jobs/index"
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit!
  end

  def check_authorization
    @job ? authorize(@job.user) : authorize()
  end
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
    <%= f.label :due_date, 'Apply by' %><br>
    <%= f.date_field :due_date %>
    <%= f.label :type, 'How did you find it?' %>
    <%= f.text_field :type %>
    <%= f.submit class: 'primary_button'%>
<% end %>

app/views/jobs/_job.html.haml
%header.list_header
  %h1
    =t('job_steps.label')

%section.list_selected_job
  %h2= @job.title
  %h3= @job.company_name

= link_to content_job_path({step: "details"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 1
    %h2
      =t('job_steps.details.label')

= link_to content_job_path({step: "research"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 2
    %h2
      =t('job_steps.research.label')

= link_to content_job_path({step: "networking"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 3
    %h2
      =t('job_steps.networking.label')

= link_to content_job_path({step: "documents"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 4
    %h2
      =t('job_steps.documents.label')

= link_to content_job_path({step: "apply"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 5
    %h2
      =t('job_steps.apply.label')

= link_to content_job_path({step: "interview"}) do
  %section.step_title.job_entry_item
    %div.number_title
      %h3 6
    %h2
      =t('job_steps.interview.label')


= link_to job_path(@job), method: :delete, data: { confirm: t('job.delete_confirmation') } do
  %section.close_job
    %h2
      = t('job.delete')

app/views/jobs/content_edit.html.haml
= render @job

- content_for :content do
  - case step
  - when 'details'
    = render 'steps/detailsEdit'

  - when 'research'
    = render 'steps/researchEdit'

  - when 'networking'
    = render 'steps/networkingEdit'

  - when 'documents'
    = render 'steps/documentsEdit'

  - when 'apply'
    = render 'steps/applyEdit'

  - when 'interview'
    = render 'steps/interviewEdit'

app/views/jobs/content_view.html.haml
= render @job

- content_for :content do
  - case step
    - when 'details'
      = render 'steps/details'

    - when 'research'
      = render 'steps/research'

    - when 'networking'
      = render 'steps/networking'

    - when 'documents'
      = render 'steps/documents'

    - when 'apply'
      = render 'steps/apply'

    - when 'interview'
      = render 'steps/interview'

    - when "contacts"
      - @job.contacts.each do |contact|
        = contact.name

    - else
      = t('job_steps.more_info')

app/views/jobs/edit.html.haml
%header
  %div 1
  %h1 Job Details

=render 'form'
=button_to 'back', @job, :class => 'secondary_button'
%section.form=render 'form'

%label Text Area
%textarea

%label Email
%input{:type => 'email'}

%label Password
%input{:type => 'password'}

%label Phone
%input{:type => 'phone'}

%label Date
%input{:type => 'date'}

%label URL
%input{:type => 'url', :placeholder => 'heyheyhey.com'}


=link_to 'Show', @job |
=link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%header.list_header
  %h1 Job Entries

- @jobs.each do |job|
  = link_to job do
    %section.job_entry_item
      %div
        %h2= job.title
        %h3= job.company_name
        %div
          %h4 % Completed

/ %button.new_job_button
/   = link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

app/views/jobs/show.html.haml
= render @job

- content_for :content do
  %section.step_content
    %h1.label
      = t('job_steps.more_info')
    = image_tag "arrow_test.svg", size: "300"