config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs do
    get :deleted_index, on: :collection
    member do
      get 'content'
      get 'content_edit'
      put :new_network
      patch :new_network
      put :new_interview
      patch :new_interview
    end
  end
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  post '/', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/views/steps/_apply.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 5
      %h1
        = t('job_steps.apply.label')
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%article.outer_container
  %section.step_content
    %label
      = t('job_steps.apply.sent')
    %p
      = @job.job_application.sent ? "Sent" : "Not sent"

    - if @job.job_application.date
      %label When did you apply?
      %p
        = @job.job_application.date

app/views/steps/_applyEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 5
      %h1
        = t('job_steps.apply.label')
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'apply'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

app/views/steps/_details.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 1
      %h1
        = t('job_steps.details.label')
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%article.outer_container
  %section.step_content
    %label Job title
    %p
      = @job.title
    %label URL
    %p
      = @job.url
    %label Company name
    %p
      = @job.company_name
    %label Apply by
    %p
      = @job.due_date
    %label How did you find this job?
    %p
      = @job.type

app/views/steps/_detailsEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 1
      %h1
        = t('job_steps.details.label')
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'details'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  = form_for @job do |f|
    = f.label :title, 'Job Title'
    = f.text_field :title
    = f.label :url
    = f.text_field :url
    = f.label :company_name
    = f.text_field :company_name
    = f.label :due_date, 'Apply By'
    = f.date_field :due_date
    = f.label :type, 'How did you find this job?'
    = f.text_field :type
    = f.submit 'Save', { class: 'primary_button' }

app/views/steps/_documents.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 4
      %h1
        = t('job_steps.documents.label')
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  %h2 Document Checklist
  %br
  %br

  %ul
    %li
      %div{class: @job.resume.resume ? 'checked' : 'unchecked'}
      %label Resume
    %li
      %div{class: @job.resume.cover_letter ? 'checked' : 'unchecked'}
      %label Cover Letter
    %li
      %div{class: @job.resume.portfolio ? 'checked' : 'unchecked'}
      %label Portfolio
    %li
      %div{class: @job.resume.certifications ? 'checked' : 'unchecked'}
      %label Certifications
    %li
      %div{class: @job.resume.references ? 'checked' : 'unchecked'}
      %label References
    %li
      %div{class: @job.resume.recommendations ? 'checked' : 'unchecked'}
      %label Recommendations

app/views/steps/_documentsEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 4
      %h1
        = t('job_steps.documents.label')
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'documents'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  %h2 Document Checklist
  %br
  %br

  = form_for @job do |g|
    = g.fields_for @job.resume do |f|
      %ul
        %li
          = f.check_box :resume
          = f.label :resume
        %li
          = f.check_box :cover_letter
          = f.label :cover_letter
        %li
          = f.check_box :portfolio
          = f.label :portfolio
        %li
          = f.check_box :certifications
          = f.label :certifications
        %li
          = f.check_box :references
          = f.label :references
        %li
          = f.check_box :recommendations
          = f.label :recommendations
    = g.submit 'Save', { class: 'primary_button' }

app/views/steps/_interview.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 6
      %h1
        = t('job_steps.interview.label')
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

app/views/steps/_interviewEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 6
      %h1
        = t('job_steps.interview.label')
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'interview'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%article.outer_container
  %section.step_content
    = form_for @job do |g|
      = g.fields_for @job.interview do |f|
        = f.radio_button :type, 'phone'
        = f.label :type_phone, "Phone Interview"
        %br
        = f.radio_button :type, 'video'
        = f.label :type_video, "Video Interview"
        %br
        = f.radio_button :type, 'person'
        = f.label :type_person, "In-Person Interview"
        %br
        = f.radio_button :type, 'other'
        = f.label :type_other, "Other"
        %br
        = f.label :date
        = f.date_field :date
      = g.submit "Save", {class: 'primary_button'}

app/views/steps/_networking.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 3
      %h1
        = t('job_steps.networking.label')
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  %label Did / do you plan to discuss this position with someone?

  - if @job.network.plans == true
    %p
      Yes
  - else
    %p
      No

  - unless @job.network.plans == false
    %label Meeting Date
    %p
      = @job.network.date

app/views/steps/_networkingEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 3
      %h1
        = t('job_steps.networking.label')
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'networking'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  %label Did / do you plan to discuss this position with someone?

  = form_for @job do |g|
    = g.fields_for @job.network do |f|
      = f.radio_button(:plans, 'no')
      = f.label :plans_no, 'No'
      = f.radio_button(:plans, 'yes')
      = f.label :plans_yes, 'Yes'
      %br

      = f.label :date, 'Meeting Date'
      = f.date_field :date

      = g.submit 'Save', { class: 'primary_button' }

app/views/steps/_research.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 2
      %h1
        = t('job_steps.research.label')
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  %label Company's mission/vision/values
  %p
    = @job.research.company_mission

  %label Company's strategic goals
  %p
    = @job.research.company_goals

  %label Favorite company product/project/service
  %p
    = @job.research.current_projects

  / %label Additional notes

app/views/steps/_researchEdit.html.haml
%header.content_header.outer_container
  %article.steptitle_grid.steptitle_flex
    %section.steptitle_width
      %div.number
        %h2 2
      %h1
        = t('job_steps.research.label')
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "edit_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "add_note_icon.svg", size: "20"
    = link_to content_edit_job_path({step: 'research'}) do
      %button.add_button
        = image_tag "add_contact_icon.svg", size: "20"

%section.step_content
  = form_for @job do |g|
    = g.fields_for @job.research do |f|
      = f.label :company_mission, "Company's mission/vision/values"
      = f.text_area :company_mission

      = f.label :company_goals, "Company's Strategic Goals"
      = f.text_area :company_goals

      = f.label :current_projects, "Favorite Company Prouct/Project/Service"
      = f.text_area :current_projects
    = g.submit 'Save', {class: 'primary_button'}