config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs do
    get :deleted_index, on: :collection
    member do
      get 'content'
      get 'content_edit'
      put :new_network
      patch :new_network
      put :new_interview
      patch :new_interview
    end
  end
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  post '/', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/views/layouts/_grid.html.haml
%aside.toolbar
  = render "layouts/toolbar"
%article.list
  = yield
%article.content
  = yield :content

app/views/layouts/_header.html.haml
// Global page header

%header.main_header
  %a.logo
    = image_tag "order_logo.svg", size: "100"
  %div.ribbon BETA
  - if current_user
    = link_to "Sign out", url_for(controller: 'sessions', action: 'destroy'), :class => "signup"
  - else
    = link_to "Sign in", url_for(controller: 'sessions', action: 'new'), :class => "signup"

app/views/layouts/_toolbar.html.haml
// Toolbar on left side

%a{:href => "/jobs/new"}
  %button.new_job_button
    = image_tag "plus.svg", size: "17"
    Add new job

  // = link_to 'Add Job', new_job_path

= link_to jobs_path do
  %button.toolbar_button
    = image_tag "dashboard_icon.svg", size: "18"
    Dashboard
- if @job
  = link_to content_job_path({step: "notes"}) do
    %button.toolbar_button
      = image_tag "notes_icon.svg", size: "16"
      View Job Notes
  = link_to content_job_path({step: "contacts"}) do
    %button.toolbar_button
      = image_tag "contacts_icon.svg", size: "18"
      View Job Contacts
= link_to deleted_index_jobs_path do
  %button.toolbar_button
    = image_tag "completed_icon.svg", size: "20"
    View Completed

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Order | Track Your Job Search Progress
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.outer_container
    %header.main-header
      = render 'layouts/header'

    - if alert || notice
      .alert-bad
        = alert
      .alert-good
        = notice

    %main
      = render 'layouts/grid'
    %footer